logging:
  level:
    root: info
    tk.mybatis: info
    org.mybatis: info
    
spring:
  profiles:
    active:
      - test
    include:
      - mybatis
      - mybatis-base
      - mybatis-message
      - mybatis-user
         