CREATE DATABASE `base_0`;

USE `base_0`;

CREATE TABLE `base` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) DEFAULT NULL,
  `ctime` DATETIME DEFAULT NULL,
  KEY `id` (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4; 

CREATE DATABASE `base_1`;

USE `base_1`;

CREATE TABLE `base` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) DEFAULT NULL,
  `ctime` DATETIME DEFAULT NULL,
  KEY `id` (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4; 
