CREATE DATABASE `user` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE `user`;

CREATE TABLE `user` (
  `id` VARCHAR(36) NOT NULL COMMENT '主键id',
  `name` VARCHAR(64) DEFAULT NULL COMMENT '用户名',
  `state` TINYINT(2) DEFAULT NULL COMMENT '用户状态',
  `description` VARCHAR(64) DEFAULT NULL COMMENT '用户描述',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE `message` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) DEFAULT NULL,
  `context` VARCHAR(64) DEFAULT NULL,
  `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `id` (`id`)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;